#' Predicted index values
#'
#' Predicted values based on the contribution of chosen places to the overall
#' index
#'
#' \code{predict.index} produces predicted values for the index of dissimilarity
#' obtained under three scenarios. These are:
#' \itemize{
#'   \item if the (residual) effects for the chosen higher-level places are set
#'   to zero
#'   \item if the shares of the two population groups are equal everywhere
#'   except for the chosen places
#'   \item if all but the chosen places are omitted from the data and the index
#'   recalculated using only those that remain (it is the ID for the chosen
#'   places alone)
#' }
#' The predictions also include:
#' \itemize{
#'    \item the impact of the chosen places upon the overall ID, where a value
#'    over 100 indicates a group of neighbourhoods with a disproportionately
#'    high impact on the ID (in the same way that \code{\link{impacts}}
#'    calculates it)
#'    \item an R-squared value. This is the proportion of the total variation in
#'    (Y - X) that is due to the chosen places, where (Y - X) are the
#'    differences between the share of population group Y and the share of
#'    population group X that are observed in each neighbourhood.
#' }
#' @param object an object of class \code{index}: a multilevel index created
#' using function \code{\link{id}}
#' @param places a character vector containing the names of the places in any of
#' the higher-level geographies for which the predictions will be made
#' @param ... additional arguments (ignored)
#' @examples
#' data(ethnicities)
#' index <- id(ethnicities, vars = c("Bangladeshi", "WhiteBrit"),
#' levels=c("LSOA","MSOA","LAD","RGN"))
#' ci <- confint(index)
#' catplot(ci)
#' # Note Tower Hamlets and Newham. Obtain the predictions for them:
#' predict(index, "Tower Hamlets")
#' predict(index, "Newham")
#' predict(index, c("Tower Hamlets","Newham"))
#' @seealso \code{\link{residuals.index}}

predict.index <- function(object, places, ...) {

  mlm <- attr(object, "mlm")
  data <- slot(mlm, "frame")
  rawdata <- slot(object, "data")
  rr <- .rvals(mlm)
  id <- object[1]

  drop <- lapply(places, function(x, df = data, rr = rr) {
    k <- which(apply(df, 2, function(y) any(y == x)))
    if(length(k) == 0) stop("Places not found")
    j <- which(df[, k] == x)
    return(list(k, j))
  })

  dummies <- matrix(0, ncol = ncol(rr), nrow = nrow(rr))
  subset <- rep(F, nrow(rr))

  for(i in 1:length(drop)) {

    k <- drop[[i]][[1]]
    j <- drop[[i]][[2]]
    rr[j, k] <- 0
    dummies[j, k] <- 1
    subset[j] <- TRUE

  }

  newid <- 0.5 * sum(abs(rowSums(rr)))

  ols <- lm(data$y ~ 0, offset = data$"(offset)", subset = subset)
  newid2 <- 0.5 * sum(abs(residuals(ols)))

  newid3 <- .idx(rawdata[subset,], c(1, 2))[1]

  ols <- lm(data$y ~ 0 + dummies, offset = data$"(offset)")

  df <- data.frame(ID1 = c(id, newid), ID2 = c(id, newid2),
                   ID3 = c(id, newid3))

  impact <- sum(subset) / length(subset)
  impact <- (df[2, 2] / df[1, 2]) / impact * 100

  df <- round(df, 3)
  rownames(df) <- c("before", "after")

  attr(df, "Rsq") <- round(summary(ols)$r.squared, 3)
  attr(df, "impact") <- round(impact, 0)
  attr(df, "places") <- places
  attr(df, "vars") <- attr(object, "vars")
  class(df) <- "predictindex"
  return(df)

}

#' Print values
#'
#' Prints predicted changes to the index of dissimilarity under various
#' scenarios generated by \code{\link{predict.index}}
#'
#' @param x output from \code{\link{predict.index}}
#' @param ... other arguments


print.predictindex <- function(x, ...) {
  cat(paste(attr(x, "vars")[1:2], collapse=" ~ "),"\n")
  df <- matrix(unlist(x), ncol = length(x))
  colnames(df) <- names(x)
  rownames(df) <- attr(x,"row.names")
  print(df)
  exclude <- attr(x,"places")
  cat("\nR-squared:", attr(x, "Rsq"), "   Impact", attr(x, "impact"))
  cat("\n\nNote:")
  cat("\nID1: if the residual effect of",exclude,"is set to zero")
  cat("\nID2: if the shares of", paste(attr(x, "vars")[1:2], collapse=" & "),
      "are equal everywhere except", exclude)
  cat("\nID3: the index value for", exclude, "alone\n")


}

